name: test 001

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Generate badge data
      id: badge_data
      run: |
        VALUE=$(date -u +'%Y-%m-%d %H:%M:%S')
        echo "value=$VALUE" >> $GITHUB_OUTPUT

    - name: Send Telegram messsage
      uses: stellarhub/telegram-message-action@v1
      with:
        chat_id: ${{ vars.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ steps.badge_data.outputs.value }}
